global:
  registry: mernregistryprod.azurecr.io
  tag: latest
  mongoUri: "mongodb://mongodb-service:27017/app_db"

gateway:
  replicaCount: 2
  port: 5000

helloService:
  replicaCount: 2
  port: 5001

profileService:
  replicaCount: 2
  port: 5002

frontend:
  replicaCount: 2
  port: 80
