apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          # Dynamically injected from your Jenkinsfile environment blocks
          image: "{{ .Values.global.registry }}/hello-service:{{ .Values.global.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-app-secrets
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-svc
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: hello-service

