apiVersion: v1
kind: Secret
metadata:
  name: mern-app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Helm will automatically encode these values to Base64 at runtime
  MONGO_URI: {{ .Values.secrets.mongoUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}

